import TaktFormal.Convergence.DynamicBehavior

namespace Convergence

variable {X : Type}

/-- Step map representing a deterministic strategy / execution step over state space `X`. -/
def StepMap (X : Type) := X → X

/-- An Invariant Region under a step map `step`. -/
def IsInvariant (R : X → Prop) (step : StepMap X) : Prop :=
  ∀ x : X, R x → R (step x)

/-- Fixed Point of a step map. -/
def IsFixedPoint (s : X) (step : StepMap X) : Prop :=
  step s = s

/-- Absorbing State: Fixed point with no outgoing transitions in transition system `T`. -/
def IsAbsorbingState (T : TransitionSystem X) (s : X) (step : StepMap X) : Prop :=
  IsFixedPoint s step ∧ ∀ y : X, ¬ T.to s y

/-- Stream generated by repeatedly applying `step` starting from `x0`. -/
def iteratedStream (step : StepMap X) (x0 : X) : StateStream X
  | 0 => x0
  | k + 1 => step (iteratedStream step x0 k)

/-- Attractor: An invariant region `A` with a basin `B` (where `B ⊇ A`) such that
    every stream initialized in `B` converges to `A`. -/
def IsAttractor (A : X → Prop) (B : X → Prop) (step : StepMap X) : Prop :=
  (∀ x : X, A x → B x) ∧
  IsInvariant A step ∧
  ∀ x0 : X, B x0 → IsConvergent (iteratedStream step x0) A

end Convergence
