import TaktFormal.Information.StationaryEmbedding
import TaktFormal.Convergence.Stability

namespace Temporal

variable {X Y Z : Type}

/-- Deterministic System Transition Dynamics (X, T) -/
structure DeterministicSystem (X : Type) where
  T : X → X

/-- Iterated Trajectory generated by initial state x0 under deterministic transition dynamics T -/
def generated_trajectory (sys : DeterministicSystem X) (x0 : X) : StateStream X :=
  Convergence.iteratedStream sys.T x0

/-- Stationary Deterministic System: Transition T is the identity map T(x) = x. -/
def stationary_system (X : Type) : DeterministicSystem X :=
  ⟨id⟩

/-- Theorem: In a stationary deterministic system (T = id), the generated trajectory
    from initial state x0 is equal to the stationary embedding of x0. -/
theorem stationary_system_generated_trajectory (x0 : X) :
    generated_trajectory (stationary_system X) x0 = Information.stationary_embedding x0 := by
  funext n
  dsimp [generated_trajectory, stationary_system, Information.stationary_embedding]
  induction n with
  | zero => rfl
  | succ n ih =>
    dsimp [Convergence.iteratedStream]
    exact ih

/-- Theorem: Static Representation Sufficiency is logically equivalent to
    Generated Trajectory Sufficiency in a stationary system (T = id). -/
theorem static_sufficiency_is_stationary_generated_sufficiency
    (P : X → Y) (f : X → Z) :
    Information.IsSufficient f P ↔
    Information.IsSufficient
      (λ (stream : StateStream X) => f (stream 0))
      (λ (stream : StateStream X) => P (stream 0)) :=
  Information.static_trajectory_sufficiency_equivalence P f

end Temporal
